/*! MFM Mega Region 2 — canonical events data. Single source of truth for events.html, index.html, and the department pages (gen218.html, women.html). Tag departmental events with "ministry": "women" | "gen218". Region-wide events have no ministry. Keep anchors unique. */
window.MFM_EVENTS = [
  {
    "date": "2026-08-23",
    "title": "Third Quarter Deliverance Service",
    "theme": "\"Breaking the Spirit of Spoiler\"",
    "time": "8:00 AM",
    "venue": "Bombay Plaza — 6989 GA-85 Ste D1, Riverdale, GA 30274",
    "ministering": "Anointed Men & Women of God",
    "host": "Pastor Francis Benede",
    "image": "img/announcements/third-quarter-deliverance.jpg",
    "alt": "MFM Third Quarter Deliverance Service — Breaking the Spirit of Spoiler, Sunday August 23, 2026, 8 AM, Riverdale, Georgia",
    "anchor": "third-quarter-deliverance",
    "dateDisplay": "Sunday, August 23, 2026",
    "description": "MFM's Third Quarter Deliverance Service under the theme \"Breaking the Spirit of Spoiler\" (Isaiah 54:15–17). Come and experience the power that breaks limitations and destroys every spoiler — and bring your instrument of trade.",
    "scripture": "No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn.|Isaiah 54:17",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-08-03",
    "endDate": "2026-10-11",
    "title": "70-Day Prayer & Fasting 2026 — \"Prayer Battle 7\"",
    "theme": "Seventy days of prayer and fasting — from the altar of revival to the battlefield of breakthrough",
    "venue": "Observed at all MFM branches (worldwide programme)",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "image": "img/announcements/prayer-battle-7.jpg",
    "images": [
      "img/announcements/prayer-battle-7.jpg",
      "img/announcements/prayer-battle-7-1.jpg",
      "img/announcements/prayer-battle-7-2.jpg",
      "img/announcements/prayer-battle-7-3.jpg",
      "img/announcements/prayer-battle-7-4.jpg",
      "img/announcements/prayer-battle-7-5.jpg",
      "img/announcements/prayer-battle-7-6.jpg",
      "img/announcements/prayer-battle-7-7.jpg"
    ],
    "alt": "MFM 70-Day Prayer and Fasting 2026 — Prayer Battle 7, August 3 to October 11, 2026",
    "anchor": "prayer-battle-7",
    "dateDisplay": "August 3 – October 11, 2026",
    "description": "MFM's annual 70-Day Prayer & Fasting Programme returns for 2026, tagged \"Prayer Battle 7.\" From August 3 to October 11, it features daily scripture reading, confessions, warfare prayers, and targeted prayer points for the church and the nation, with praise and worship. Daily fast-breaking times (local): Monday & Friday — 5 PM; Tuesday, Wednesday, Thursday, Saturday & Sunday — 2 PM. The programme runs in 7 sections of 10 days each (70 days total), with a compulsory sectional vigil at the end of every section, a one-year Bible reading plan, and a closing Thanksgiving service in October. The \"Prayer Battle\" booklet is available in hard copy at all MFM regions, branches, and bookshops, and as a digital download.",
    "features": [
      "70 Days of Prayer & Fasting",
      "Daily Warfare Prayers",
      "One-Year Bible Reading Plan",
      "Sectional Vigils",
      "Thanksgiving Service"
    ],
    "scripture": "Howbeit this kind goeth not out but by prayer and fasting.|Matthew 17:21",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-04-24",
    "title": "Night of Worship & Wonders",
    "theme": "A Special Prayer Vigil",
    "time": "10:00 PM CST",
    "venue": "306 N Greenville Ave, Richardson, TX 75081",
    "ministering": "Pastor David Popoola — ASRO, MFM Dallas Texas",
    "image": "img/announcements/night-of-worship.jpg",
    "alt": "Night of Worship and Wonders — Friday April 24, 2026, MFM Dallas Texas",
    "anchor": "night-of-worship",
    "dateDisplay": "Friday, April 24, 2026",
    "description": "A powerful night of prophetic worship, prophetic prayer, healing, and breakthrough. Come expecting the move of God — the God of Elijah answers by fire.",
    "features": [
      "Prophetic Worship",
      "Prophetic Prayer",
      "Healing Breakthrough",
      "Divine Intervention"
    ],
    "badgeStyle": "fire"
  },
  {
    "date": "2026-05-03",
    "endDate": "2026-08-31",
    "title": "Foundation & Membership Class — Tampa",
    "theme": "Build a strong foundation in faith",
    "time": "Every Sunday from May 2026",
    "venue": "MFM Tampa Florida",
    "host": "MFM Tampa Florida Assembly Pastor",
    "image": "img/announcements/tampa-membership-class.jpg",
    "alt": "MFM Tampa Florida Foundation and Membership Class — Sundays from May 2026",
    "anchor": "tampa-membership-class",
    "dateDisplay": "Every Sunday, May – August 2026",
    "description": "A structured membership and foundation class for new believers and those desiring a deeper understanding of the faith. Build your walk with God on solid scriptural ground.",
    "badgeStyle": "gold"
  },
  {
    "date": "2026-05-16",
    "title": "Women Conference — Dallas",
    "theme": "\"A Date with my Lord + Lover\"",
    "time": "10:00 AM – 2:00 PM",
    "venue": "306 Greenville Ave, Richardson, TX 75081",
    "ministering": "Pastor Olumide Oni & Pastor (Mrs.) Oluwatoyin Oni",
    "host": "Pastor David & Pastor (Mrs.) Adenike Popoola",
    "image": "img/announcements/women-conference-dallas.jpg",
    "alt": "Women Conference Dallas flyer — Saturday May 16, 2026",
    "anchor": "women-conference-dallas",
    "dateDisplay": "Saturday, May 16, 2026",
    "description": "A special women's conference bringing together the women of MFM for teaching, prayer, fellowship, and empowerment.",
    "scripture": "God is in the midst of her; she shall not be moved: God shall help her, and that right early.|Psalm 46:5",
    "badgeStyle": "gold",
    "ministry": "women"
  },
  {
    "date": "2026-06-20",
    "title": "Gen218 Prayer Conference 2026",
    "theme": "\"Divine Alignment\"",
    "time": "12:00 PM EST",
    "venue": "Online via Zoom",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "host": "MFM North America Gen218 Coordinators",
    "image": "img/announcements/gen218-prayer-conference.jpg",
    "alt": "Gen218 Prayer Conference 2026 — June 20, Divine Alignment",
    "anchor": "gen218-prayer-conference",
    "dateDisplay": "Saturday, June 20, 2026",
    "description": "A virtual prayer programme for Christian singles across North America — prayers, teaching, healing, and prophetic declarations for divine alignment in every area of life.",
    "features": [
      "Prayers",
      "Teaching",
      "Healing",
      "Prophetic Declarations"
    ],
    "badgeStyle": "fire",
    "ministry": "gen218"
  },
  {
    "date": "2026-07-16",
    "endDate": "2026-07-19",
    "title": "International Youth Convention 2026",
    "theme": "Registration is now open",
    "venue": "MFM USA Headquarters — 10000 Kleckley Dr, Houston, TX 77075",
    "host": "MFM Youth Ministry",
    "link": "https://mfmym.org/iyc2026/",
    "image": "img/announcements/iyc-2026.jpg",
    "alt": "International Youth Convention 2026 — July 16 to 19, registration is now open",
    "anchor": "iyc-2026",
    "dateDisplay": "July 16 – 19, 2026",
    "description": "The International Youth Convention brings together young believers from across MFM worldwide for worship, teaching, spiritual warfare, and fellowship. Registration is now open.",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-08-01",
    "endDate": "2026-08-03",
    "title": "Command the Month — El Roi",
    "theme": "\"El Roi — The God That Sees\"",
    "time": "10:00 PM CST nightly",
    "venue": "Online via Zoom",
    "ministering": "Pastor (Dr.) Segun Obatusin — MFM Austin, Texas",
    "image": "img/announcements/command-the-month-austin.jpg",
    "alt": "Command the Month, El Roi — MFM Austin Texas, August 1 to 3, 2026, 10 PM CST",
    "anchor": "command-the-month-austin",
    "dateDisplay": "August 1 – 3, 2026",
    "description": "A three-night prayer program from MFM Austin, Texas to command the month by fire under the banner of El Roi — the God that sees. Take your stand at the start of the month and press for divine intervention.",
    "scripture": "And she called the name of the LORD that spake unto her, Thou God seest me.|Genesis 16:13",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-08-07",
    "endDate": "2026-08-09",
    "title": "Back to School Prayers — Tampa",
    "theme": "For Students — Divine Protection · Academic Excellence · Bright Future",
    "time": "Fri 7:00 PM · Sat 3:00 PM · Sun 10:00 AM",
    "venue": "MFM Tampa, Florida — 4618 North Florida Avenue, Tampa, FL 33603",
    "ministering": "Pastor Kehinde Olajide — Assistant Senior Regional Overseer, MFM Tampa Florida",
    "image": "img/announcements/back-to-school-tampa.jpg",
    "alt": "Back to School Prayers for Students — MFM Tampa Florida, August 7 to 9, 2026",
    "anchor": "back-to-school-tampa",
    "dateDisplay": "August 7 – 9, 2026",
    "description": "A three-day back-to-school prayer gathering from MFM Tampa covering students for the new academic year — praying for divine protection, academic excellence, and a bright future.",
    "features": [
      "Divine Protection",
      "Academic Excellence",
      "Bright Future"
    ],
    "badgeStyle": "gold"
  },
  {
    "date": "2026-08-07",
    "endDate": "2026-08-09",
    "title": "Back to School Prayers — Northwest Houston",
    "theme": "For Students — Divine Protection · Academic Excellence · Destiny Fulfillment",
    "time": "Fri & Sat 9:00 AM – 3:00 PM · Sun 9:00 AM – 1:00 PM",
    "venue": "MFM Northwest Houston — 9110 Jones Road, Suite 123, Houston, TX 77065",
    "ministering": "Pastor Morenike Coker — Zonal Pastor, Houston, Texas",
    "image": "img/announcements/back-to-school-nw-houston.jpg",
    "alt": "Back to School Prayers for Students — MFM Northwest Houston, August 7 to 9, 2026",
    "anchor": "back-to-school-nw-houston",
    "dateDisplay": "August 7 – 9, 2026",
    "description": "A three-day Back-to-School Bootcamp from MFM Northwest Houston, welcoming students into the 2026–2027 academic year with prayers for divine protection, academic excellence, a bright future, and destiny fulfillment. Free lunch provided daily (12:30 – 1:00 PM).",
    "features": [
      "Divine Protection",
      "Academic Excellence",
      "Destiny Fulfillment"
    ],
    "badgeStyle": "gold"
  },
  {
    "date": "2026-08-01",
    "endDate": "2026-08-31",
    "title": "Spiritual Refresh — Ephesians Series",
    "theme": "A journey through the teachings of Apostle Paul",
    "time": "Throughout August",
    "venue": "MFM Tampa, Florida",
    "host": "MFM Tampa Florida",
    "image": "img/announcements/spiritual-refresh-tampa.jpg",
    "alt": "Spiritual Refresh — Ephesians teaching series, MFM Tampa Florida, August 2026",
    "anchor": "spiritual-refresh-tampa",
    "dateDisplay": "Throughout August 2026",
    "description": "A month-long teaching series journeying through Paul's letter to the Ephesians, paired with a challenge to read the New Testament a chapter a day. Refresh your spirit, renew your mind, strengthen your faith, and empower your purpose.",
    "features": [
      "Refresh your spirit",
      "Renew your mind",
      "Strengthen your faith",
      "Empower your purpose"
    ],
    "badgeStyle": "gold"
  },
  {
    "date": "2026-09-16",
    "title": "The Great North Carolina Deliverance Crusade & Church Property Dedication",
    "theme": "A Great Deliverance Crusade",
    "venue": "The Alliance Convention Center — 1214 Turrentine Street, Burlington, NC 27215",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "host": "Pastor Ebenezer Afolabi (Area Overseer, MFM Burlington NC) · Pastor Olumide Oni (PRO, Mega Region 2)",
    "image": "img/announcements/nc-deliverance-crusade.jpg",
    "alt": "The Great North Carolina Deliverance Crusade & Church Property Dedication — Burlington, NC, September 16–17, 2026",
    "anchor": "nc-deliverance-crusade",
    "video": "https://youtu.be/OuY6DPpbhv4",
    "link": "https://www.eventbrite.com/e/the-great-north-carolina-deliverance-crusade-with-dr-dk-olukoya-tickets-1996920415719?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=wsa&aff=ebdsshwebmobile",
    "dateDisplay": "September 16 – 17, 2026",
    "description": "Come with expectation — a season of power, deliverance, healing, and breakthrough for you and your household. All are welcome; bring your family and friends.",
    "badgeStyle": "fire",
    "endDate": "2026-09-17",
    "schedule": [
      { "label": "Church Property Dedication", "shortDate": "Sep 16", "when": "Wednesday, Sep 16 · 5:00 PM", "venue": "MFM Burlington", "address": "511 James Street, Burlington, NC 27217" },
      { "label": "The Deliverance Crusade", "shortDate": "Sep 17", "when": "Thursday, Sep 17 · 5:00 PM", "venue": "The Alliance Convention Center", "address": "1214 Turrentine Street, Burlington, NC 27215" }
    ]
  },
  {
    "date": "2026-10-10",
    "title": "Women's Retreat — Rekindling the Altar",
    "theme": "\"Rekindling the Altar\" · 7 Hours at the Master's Feet",
    "time": "9:00 AM – 4:00 PM",
    "venue": "MFM Banquet Hall — 10000 Kleckley Dr, Houston, TX 77075",
    "ministering": "Anointed Ministers of God",
    "host": "MFM Women Foundation, Mega Region 2 USA",
    "image": "img/announcements/womens-retreat.jpg",
    "alt": "Women's Retreat, Rekindling the Altar — Saturday October 10, 2026, MFM Women Foundation Mega Region 2 USA",
    "anchor": "womens-retreat",
    "link": "https://www.eventbrite.com/e/womens-retreat-2026-rekindling-the-altar-mfm-mega-region-2-tickets-1996924949279?aff=oddtdtcreator",
    "dateDisplay": "Saturday, October 10, 2026",
    "description": "A women's retreat under the Women Foundation of Mega Region 2 — seven hours at the Master's feet to rekindle the fire on the altar. A day of prayer, worship, the Word, fellowship, and transformation. Empowered to pray, equipped to serve, engaged to transform.",
    "scripture": "The fire shall ever be burning upon the altar; it shall never go out.|Leviticus 6:13",
    "badgeStyle": "gold",
    "ministry": "women"
  },
  {
    "date": "2026-09-19",
    "title": "The Great Florida Deliverance Crusade & Church Property Dedication",
    "theme": "Expect. Receive. Testify — power, deliverance, healing & breakthrough",
    "venue": "Yuengling Center (USF) — 12499 USF Bull Run Drive, Tampa, FL 33620",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "host": "Pastor Kehinde Olajide (ASRO, MFM Florida) · Pastor Olumide Oni (PRO, Mega Region 2)",
    "image": "img/announcements/florida-deliverance-crusade.jpg",
    "alt": "The Great Florida Deliverance Crusade & Church Property Dedication — Tampa, FL, September 19–20, 2026",
    "anchor": "florida-deliverance-crusade",
    "video": "https://www.youtube.com/watch?v=ZbDw9eUwOKs",
    "link": "https://www.eventbrite.com/e/the-great-florida-deliverance-crusade-with-dr-dk-olukoya-tickets-1996922802859?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=wsa&aff=ebdsshwebmobile",
    "dateDisplay": "September 19 – 20, 2026",
    "description": "Come with expectation — the tangible power of God for deliverance, healing, and breakthrough over your life and household. All are welcome; bring your family and friends.",
    "badgeStyle": "fire",
    "endDate": "2026-09-20",
    "schedule": [
      { "label": "Church Property Dedication", "shortDate": "Sep 19", "when": "Saturday, Sep 19 · 5:00 PM", "venue": "MFM Tampa", "address": "4618 North Florida Avenue, Tampa, FL 33603" },
      { "label": "The Deliverance Crusade", "shortDate": "Sep 20", "when": "Sunday, Sep 20 · 4:00 PM", "venue": "Yuengling Center (USF)", "address": "12499 USF Bull Run Drive, Tampa, FL 33620" }
    ]
  },
  {
    "date": "2026-10-10",
    "title": "Gen218 Regional Prayer Conference",
    "theme": "\"And God said…\" (Genesis 2:18)",
    "time": "10:00 AM CST",
    "venue": "MFM Prayer City — 10000 Kleckley Dr, Houston, TX 77075",
    "host": "Gen218, Mega Region 2 USA",
    "image": "img/announcements/gen218-regional-conference.jpg",
    "alt": "Gen218 Regional Prayer Conference — Saturday October 10, 2026, MFM Prayer City",
    "anchor": "gen218-regional-conference",
    "dateDisplay": "Saturday, October 10, 2026",
    "description": "A regional prayer conference for singles under Gen218 — a time for powerful prayers, deliverance, and sound teaching on meeting your spouse and marital settlement. Come expectant, leave transformed.",
    "features": [
      "Powerful Prayers",
      "Deliverance",
      "Sound Teaching",
      "Marital Settlement"
    ],
    "badgeStyle": "fire",
    "ministry": "gen218"
  },
  {
    "date": "2026-11-19",
    "title": "The Great Nashville Tennessee Deliverance Crusade",
    "theme": "A Great Deliverance Crusade",
    "time": "5:00 PM",
    "venue": "Nashville, Tennessee (venue to be announced)",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "host": "Pastor Lovena Okeke (Host)",
    "image": "img/announcements/nashville-deliverance-crusade.jpg",
    "alt": "The Great Nashville Tennessee Deliverance Crusade — November 19, 2026, ministering Dr. D.K. Olukoya",
    "anchor": "nashville-deliverance-crusade",
    "dateDisplay": "November 19, 2026",
    "description": "A great deliverance crusade in Nashville, Tennessee with the General Overseer, Dr. D.K. Olukoya — a night of fire, deliverance, and the demonstration of the power of God. Venue to be announced.",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-08-09",
    "title": "Back to School Prayers — Rehoboth Center",
    "theme": "Covering our children with prayer, preparing them for purpose",
    "time": "8:00 AM prompt",
    "venue": "MFM Rehoboth Center — 12342 Bissonnet Street, Houston, TX 77099",
    "ministering": "Pastor Lekan Ademakin & other anointed ministers of God",
    "image": "img/announcements/back-to-school-rehoboth.jpg",
    "alt": "Back to School Prayers — MFM Rehoboth Center, Houston — Sunday August 9, 2026",
    "anchor": "back-to-school-rehoboth",
    "dateDisplay": "Sunday, August 9, 2026",
    "description": "A special back-to-school prayer gathering at MFM Rehoboth Center — covering our students, teachers, parents, and schools with prayer for divine protection, wisdom, academic excellence, and a bright future as a new school season begins. Come with a bottle of oil.",
    "features": [
      "Divine Protection",
      "Wisdom & Excellence",
      "Covering for Students & Teachers",
      "A Bright Future"
    ],
    "scripture": "Commit thy works unto the LORD, and thy thoughts shall be established.|Proverbs 16:3",
    "badgeStyle": "gold"
  },
  {
    "date": "2026-08-22",
    "title": "Zonal Women's Conference 2026 — \"Prevailing Women\"",
    "theme": "Prevailing Women",
    "time": "10:00 AM – 5:00 PM EST",
    "venue": "MFM Revival Center — 3480 Howell St NW, Duluth, GA 30096",
    "ministering": "Anointed Ministers of God",
    "image": "img/announcements/zonal-womens-conference.jpg",
    "alt": "Zonal Women's Conference 2026 — Prevailing Women, Atlanta Zone, August 22, 2026",
    "anchor": "zonal-womens-conference",
    "ministry": "women",
    "dateDisplay": "Saturday, August 22, 2026",
    "description": "The Women Foundation, Mega Region 2 — Atlanta Zone presents the 2026 Zonal Women's Conference, \"Prevailing Women.\" A gathering of women for prayer, worship, the Word, and empowerment. Come and be empowered to prevail.",
    "scripture": "She openeth her mouth with wisdom; and in her tongue is the law of kindness.|Proverbs 31:26",
    "badgeStyle": "gold"
  },
  {
    "date": "2026-12-11",
    "title": "Couples Night",
    "theme": "For married & intending couples",
    "time": "7:00 PM",
    "venue": "Marriott Houston Energy Corridor — 16011 Katy Freeway, Houston, TX 77094",
    "host": "MFM Mega Region 2 USA",
    "image": "img/announcements/couples-night.jpg",
    "alt": "Couples Night — MFM Mega Region 2, Friday December 11, 2026, Marriott Houston Energy Corridor, Houston TX",
    "anchor": "couples-night",
    "dateDisplay": "Friday, December 11, 2026",
    "description": "An evening set apart for couples — a time to be strengthened, refreshed, and blessed together in the presence of God. Come expecting.",
    "badgeStyle": "gold"
  },
  {
    "date": "2026-12-12",
    "title": "Thanksgiving Service",
    "theme": "Come Expecting",
    "time": "10:00 AM",
    "venue": "MFM Banquet Hall, Prayer City — 10000 Kleckley Dr, Houston, TX 77075",
    "host": "MFM Mega Region 2 USA",
    "image": "img/announcements/thanksgiving-service.jpg",
    "alt": "Thanksgiving Service — MFM Mega Region 2, Saturday December 12, 2026, MFM Banquet Hall Prayer City, Houston TX",
    "anchor": "thanksgiving-service",
    "dateDisplay": "Saturday, December 12, 2026",
    "description": "A gathering to give God thanks and praise for His faithfulness, His power, and all He has done. He is faithful, He is able, and He will do it again.",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-08-29",
    "title": "Women Foundation Florida — August Meeting",
    "theme": "You Are Welcome",
    "time": "6:00 PM",
    "venue": "Online via Zoom",
    "host": "MFM Women Foundation Florida",
    "image": "img/announcements/women-foundation-fl-august.jpg",
    "alt": "MFM Women Foundation Florida — August Meeting, Saturday August 29, 2026, 6:00 PM on Zoom",
    "anchor": "women-foundation-fl-august",
    "dateDisplay": "Saturday, August 29, 2026",
    "description": "The MFM Women Foundation Florida invites all women across the Florida zones — Broward, Jacksonville, Miami, Orlando, Tallahassee and Tampa — to the August meeting on Zoom. Come and be blessed. The Zoom link is shared on request — please contact your zone's Women Foundation leader to join.",
    "ministry": "women",
    "badgeStyle": "gold"
  }
];
