/*! MFM Mega Region 2 — canonical events data. Single source of truth for events.html, index.html,
   the department pages (gen218.html, women.html), the event detail pages and the static fallbacks
   generated by tools/build_site.py.
   - Only current/upcoming programmes live here (standing rule: never show past programmes).
   - Timing: "start"/"end" are LOCAL wall-clock times ("YYYY-MM-DDTHH:MM") in the IANA zone "tz"
     (America/Chicago = CT, America/New_York = ET). Without "start" the event is all-day from
     "date" to "endDate". Everything (past/upcoming, countdowns, calendar links, schema) is derived
     from these fields by window.MFM_EVT below — never from the free-text "time" label.
   - Tag departmental events with "ministry": "women" | "gen218". Keep anchors unique.
   - "page" = clean URL of the event's own detail page, when one exists. */
window.MFM_EVENTS = [
  {
    "date": "2026-08-03",
    "tz": "America/Chicago",
    "page": "/events/prayer-battle-7",
    "endDate": "2026-10-11",
    "title": "70-Day Prayer & Fasting 2026 — \"Prayer Battle 7\"",
    "theme": "Seventy days of prayer and fasting — from the altar of revival to the battlefield of breakthrough",
    "venue": "Observed at all MFM branches (worldwide programme)",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "image": "img/announcements/prayer-battle-7.jpg",
    "images": [
      "img/announcements/prayer-battle-7.jpg",
      "img/announcements/prayer-battle-7-1.jpg",
      "img/announcements/prayer-battle-7-2.jpg",
      "img/announcements/prayer-battle-7-3.jpg",
      "img/announcements/prayer-battle-7-4.jpg",
      "img/announcements/prayer-battle-7-5.jpg",
      "img/announcements/prayer-battle-7-6.jpg",
      "img/announcements/prayer-battle-7-7.jpg"
    ],
    "alt": "MFM 70-Day Prayer and Fasting 2026 — Prayer Battle 7, August 3 to October 11, 2026",
    "anchor": "prayer-battle-7",
    "dateDisplay": "August 3 – October 11, 2026",
    "description": "MFM's annual 70-Day Prayer & Fasting Programme returns for 2026, tagged \"Prayer Battle 7.\" From August 3 to October 11, it features daily scripture reading, confessions, warfare prayers, and targeted prayer points for the church and the nation, with praise and worship. Daily fast-breaking times (local): Monday & Friday — 5 PM; Tuesday, Wednesday, Thursday, Saturday & Sunday — 2 PM. The programme runs in 7 sections of 10 days each (70 days total), with a compulsory sectional vigil at the end of every section, a one-year Bible reading plan, and a closing Thanksgiving service in October. The \"Prayer Battle\" booklet is available in hard copy at all MFM regions, branches, and bookshops, and as a digital download.",
    "features": [
      "70 Days of Prayer & Fasting",
      "Daily Warfare Prayers",
      "One-Year Bible Reading Plan",
      "Sectional Vigils",
      "Thanksgiving Service"
    ],
    "scripture": "Howbeit this kind goeth not out but by prayer and fasting.|Matthew 17:21",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-10-10",
    "start": "2026-10-10T09:00",
    "end": "2026-10-10T16:00",
    "tz": "America/Chicago",
    "page": "/events/womens-retreat",
    "title": "Women's Retreat — Rekindling the Altar",
    "theme": "\"Rekindling the Altar\" · 7 Hours at the Master's Feet",
    "time": "9:00 AM – 4:00 PM CT",
    "venue": "MFM Banquet Hall — 10000 Kleckley Dr, Houston, TX 77075",
    "ministering": "Anointed Ministers of God",
    "host": "MFM Women Foundation, Mega Region 2 USA",
    "image": "img/announcements/womens-retreat.jpg",
    "alt": "Women's Retreat, Rekindling the Altar — Saturday October 10, 2026, MFM Women Foundation Mega Region 2 USA",
    "anchor": "womens-retreat",
    "link": "https://www.eventbrite.com/e/womens-retreat-2026-rekindling-the-altar-mfm-mega-region-2-tickets-1996924949279?aff=oddtdtcreator",
    "dateDisplay": "Saturday, October 10, 2026",
    "description": "A women's retreat under the Women Foundation of Mega Region 2 — seven hours at the Master's feet to rekindle the fire on the altar. A day of prayer, worship, the Word, fellowship, and transformation. Empowered to pray, equipped to serve, engaged to transform.",
    "scripture": "The fire shall ever be burning upon the altar; it shall never go out.|Leviticus 6:13",
    "badgeStyle": "gold",
    "ministry": "women"
  },
  {
    "date": "2026-10-10",
    "start": "2026-10-10T10:00",
    "tz": "America/Chicago",
    "page": "/events/gen218-regional-conference",
    "title": "Gen218 Regional Prayer Conference",
    "theme": "\"And God said…\" (Genesis 2:18)",
    "time": "10:00 AM CT",
    "venue": "MFM Prayer City — 10000 Kleckley Dr, Houston, TX 77075",
    "host": "Gen218, Mega Region 2 USA",
    "image": "img/announcements/gen218-regional-conference.jpg",
    "alt": "Gen218 Regional Prayer Conference — Saturday October 10, 2026, MFM Prayer City",
    "anchor": "gen218-regional-conference",
    "link": "https://www.eventbrite.com/e/gen218-regional-prayer-conference-2026-mfm-mega-region-2-tickets-1996929263182",
    "dateDisplay": "Saturday, October 10, 2026",
    "description": "A regional prayer conference for singles under Gen218 — a time for powerful prayers, deliverance, and sound teaching on meeting your spouse and marital settlement. Come expectant, leave transformed.",
    "features": [
      "Powerful Prayers",
      "Deliverance",
      "Sound Teaching",
      "Marital Settlement"
    ],
    "badgeStyle": "fire",
    "ministry": "gen218"
  },
  {
    "date": "2026-10-30",
    "start": "2026-10-30T20:00",
    "tz": "America/New_York",
    "title": "Hallowed With Jesus Movie Night",
    "pageTitle": "Hallowed With Jesus Movie Night \u2014 Agb\u00e1ra \u0143l\u00e1: The Return",
    "theme": "Experience \u201cAgb\u00e1ra \u0143l\u00e1: The Return\u201d",
    "time": "8:00 PM ET",
    "venue": "MFM Revival Center, Duluth Branch \u2014 3480 Howell St, Duluth, GA 30096",
    "host": "Pastor Abel & Juliana Michael",
    "image": "img/announcements/movie-night-agbara-nla.jpg",
    "alt": "Hallowed With Jesus Movie Night \u2014 Experience Agb\u00e1ra \u0143l\u00e1: The Return, with Pastor Abel & Juliana Michael, Friday October 30, 2026, 8 PM, MFM Revival Center Duluth Branch, Atlanta GA. Free popcorn available.",
    "anchor": "movie-night-agbara-nla",
    "page": "/events/movie-night-agbara-nla",
    "dateDisplay": "Friday, October 30, 2026",
    "description": "Hallowed With Jesus Movie Night at MFM Revival Center, Duluth Branch \u2014 experience the film \u201cAgb\u00e1ra \u0143l\u00e1: The Return\u201d with Pastor Abel & Juliana Michael. Free popcorn available.",
    "badgeStyle": "gold"
  },
  {
    "date": "2026-11-19",
    "start": "2026-11-19T17:00",
    "tz": "America/Chicago",
    "page": "/events/nashville-deliverance-crusade",
    "title": "The Great Nashville Tennessee Deliverance Crusade",
    "theme": "Dry Bones Shall Live Again",
    "time": "5:00 PM CT",
    "venue": "The Forum — 705 Rivergate Pkwy, Goodlettsville, TN 37072",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "host": "Pastor Lovena Okeke (Host)",
    "image": "img/announcements/nashville-deliverance-crusade.jpg",
    "alt": "The Great Nashville Tennessee Deliverance Crusade — November 19, 2026, ministering Dr. D.K. Olukoya",
    "link": "https://www.eventbrite.com/e/the-great-tennessee-deliverance-crusade-with-dr-dk-olukoya-tickets-1999884722039",
    "anchor": "nashville-deliverance-crusade",
    "dateDisplay": "November 19, 2026",
    "description": "A great deliverance crusade in Nashville, Tennessee with the General Overseer, Dr. D.K. Olukoya — a night of fire, deliverance and breakthrough. Theme: Dry Bones Shall Live Again (Ezekiel 37:4). Venue: The Forum, Goodlettsville, TN.",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-11-21",
    "start": "2026-11-21T16:00",
    "tz": "America/Chicago",
    "page": "/events/dallas-deliverance-crusade",
    "title": "The Great Dallas Deliverance Crusade",
    "theme": "“Anticipate” — power, deliverance, healing & breakthrough",
    "time": "4:00 PM CST",
    "venue": "Southfork Ranch — 3700 Hogge Dr, Parker, TX 75002",
    "ministering": "Dr. D.K. Olukoya — General Overseer, MFM Worldwide",
    "host": "MFM Dallas Texas",
    "image": "img/announcements/dallas-deliverance-crusade.jpg",
    "alt": "The Great Dallas Deliverance Crusade (GDDC) with Dr. D.K. Olukoya — Saturday November 21, 2026, 4 PM CST, Southfork Ranch, Parker, TX",
    "anchor": "dallas-deliverance-crusade",
    "link": "https://www.eventbrite.com/e/the-great-dallas-deliverance-crusade-with-dr-dk-olukoya-tickets-1999884755138",
    "dateDisplay": "Saturday, November 21, 2026",
    "description": "The Great Dallas Deliverance Crusade (GDDC) with Dr. D.K. Olukoya, General Overseer of MFM Worldwide, hosted by MFM Dallas Texas. Come with expectation — a season of power, deliverance, healing and breakthrough for you and your household. All are welcome; bring your family and friends.",
    "badgeStyle": "fire"
  },
  {
    "date": "2026-12-11",
    "start": "2026-12-11T19:00",
    "tz": "America/Chicago",
    "page": "/events/couples-night",
    "title": "Couples Night",
    "theme": "For married & intending couples",
    "time": "7:00 PM CT",
    "venue": "Marriott Houston Energy Corridor — 16011 Katy Freeway, Houston, TX 77094",
    "host": "MFM Mega Region 2 USA",
    "image": "img/announcements/couples-night.jpg",
    "alt": "Couples Night — MFM Mega Region 2, Friday December 11, 2026, Marriott Houston Energy Corridor, Houston TX",
    "anchor": "couples-night",
    "link": "https://www.eventbrite.com/e/couples-night-2026-mfm-mega-region-2-usa-tickets-2003175525922",
    "dateDisplay": "Friday, December 11, 2026",
    "description": "An evening set apart for couples — a time to be strengthened, refreshed, and blessed together in the presence of God. Come expecting.",
    "badgeStyle": "gold"
  },
  {
    "date": "2026-12-12",
    "start": "2026-12-12T10:00",
    "tz": "America/Chicago",
    "page": "/events/thanksgiving-service",
    "title": "Thanksgiving Service",
    "theme": "Come Expecting",
    "time": "10:00 AM CT",
    "venue": "MFM Banquet Hall, Prayer City — 10000 Kleckley Dr, Houston, TX 77075",
    "host": "MFM Mega Region 2 USA",
    "image": "img/announcements/thanksgiving-service.jpg",
    "alt": "Thanksgiving Service — MFM Mega Region 2, Saturday December 12, 2026, MFM Banquet Hall Prayer City, Houston TX",
    "anchor": "thanksgiving-service",
    "link": "https://www.eventbrite.com/e/thanksgiving-service-2026-mfm-mega-region-2-usa-tickets-1999884820333",
    "dateDisplay": "Saturday, December 12, 2026",
    "description": "A gathering to give God thanks and praise for His faithfulness, His power, and all He has done. He is faithful, He is able, and He will do it again.",
    "badgeStyle": "fire"
  }
];

/* ============================================================================
   MFM_EVT — shared, time-zone-aware helpers used by every event surface
   (home spotlight + dock, events page + modal, Women, Gen218, detail pages).
   ========================================================================== */
window.MFM_EVT = (function () {
  var DEF_TZ = 'America/Chicago';
  var ABBR = { 'America/Chicago': 'CT', 'America/New_York': 'ET' };
  function pad(n) { return ('0' + n).slice(-2); }
  /* Offset (minutes) of zone `tz` at instant `ms`. */
  function offsetAt(ms, tz) {
    try {
      var f = new Intl.DateTimeFormat('en-US', { timeZone: tz, hourCycle: 'h23', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' });
      var p = {}; f.formatToParts(new Date(ms)).forEach(function (x) { p[x.type] = x.value; });
      var asUTC = Date.UTC(+p.year, +p.month - 1, +p.day, +p.hour % 24, +p.minute, +p.second);
      return Math.round((asUTC - ms) / 60000);
    } catch (e) { return -360; }
  }
  /* Wall-clock "YYYY-MM-DDTHH:MM[:SS]" in zone tz -> Date (the real instant). */
  function zoned(local, tz) {
    var m = String(local || '').match(/^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}):(\d{2})(?::(\d{2}))?)?/);
    if (!m) return new Date(NaN);
    var guess = Date.UTC(+m[1], +m[2] - 1, +m[3], +(m[4] || 0), +(m[5] || 0), +(m[6] || 0));
    var off = offsetAt(guess, tz || DEF_TZ);
    var ms = guess - off * 60000;
    var off2 = offsetAt(ms, tz || DEF_TZ);
    if (off2 !== off) ms = guess - off2 * 60000;
    return new Date(ms);
  }
  function tzOf(e) { return (e && e.tz) || DEF_TZ; }
  function start(e) { return e.start ? zoned(e.start, tzOf(e)) : zoned(e.date + 'T00:00', tzOf(e)); }
  /* Without an explicit end, a timed event is treated as ending at the end of its last day. */
  function end(e) { return e.end ? zoned(e.end, tzOf(e)) : zoned((e.endDate || e.date) + 'T23:59:59', tzOf(e)); }
  function isPast(e, now) { return end(e).getTime() < (now || new Date()).getTime(); }
  function isLive(e, now) { var n = (now || new Date()).getTime(); return start(e).getTime() <= n && n <= end(e).getTime(); }
  function upcoming(list, now) {
    return (list || []).filter(function (e) { return e && e.date && !isPast(e, now); })
      .sort(function (a, b) {
        var pa = a.pinned ? 0 : 1, pb = b.pinned ? 0 : 1; if (pa !== pb) return pa - pb;
        function k(x) { return isLive(x, now) ? end(x).getTime() : start(x).getTime(); }
        return k(a) - k(b);
      });
  }
  /* "YYYY-MM-DD" for "now" in a zone (used by the recurring programmes). */
  function todayIn(tz, now) {
    var f = new Intl.DateTimeFormat('en-CA', { timeZone: tz || DEF_TZ, year: 'numeric', month: '2-digit', day: '2-digit' });
    return f.format(now || new Date());
  }
  function abbr(e) { return ABBR[tzOf(e)] || ''; }
  /* Local wall time of an instant in a zone, e.g. "6:00 PM". */
  function clock(d, tz) {
    return new Intl.DateTimeFormat('en-US', { timeZone: tz, hour: 'numeric', minute: '2-digit' }).format(d);
  }
  function wall(local) { var s = String(local).replace(/[-:]/g, ''); if (s.length === 8) return s; return (s + '0000').slice(0, 13) + '00'; }
  function plusHours(local, h) {
    var m = String(local).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/); if (!m) return local;
    var d = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4] + h, +m[5]));
    return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate()) + 'T' + pad(d.getUTCHours()) + ':' + pad(d.getUTCMinutes());
  }
  function nextDay(ymd) { var p = ymd.split('-'); var d = new Date(Date.UTC(+p[0], +p[1] - 1, +p[2] + 1)); return d.getUTCFullYear() + pad(d.getUTCMonth() + 1) + pad(d.getUTCDate()); }
  /* Google Calendar link: timed (with ctz) when a start time is known, otherwise all-day. */
  function gcal(e, origin) {
    var dates;
    if (e.start) {
      var en = e.end || plusHours(e.start, 2); /* no published end time: 2-hour calendar block */
      dates = wall(e.start) + '/' + wall(en) + '&ctz=' + encodeURIComponent(tzOf(e));
    } else {
      dates = String(e.date).replace(/-/g, '') + '/' + nextDay(e.endDate || e.date);
    }
    var details = (e.description || '') + (e.time ? '\n\nTime: ' + e.time : '') + (origin && e.page ? '\n\n' + origin + e.page : '');
    return 'https://calendar.google.com/calendar/render?action=TEMPLATE&text=' + encodeURIComponent(e.title || '') +
      '&dates=' + dates + '&details=' + encodeURIComponent(details) + '&location=' + encodeURIComponent(e.venue || '');
  }
  function isoOffset(local, tz) {
    var d = zoned(local, tz), off = offsetAt(d.getTime(), tz), sign = off < 0 ? '-' : '+', a = Math.abs(off);
    return String(local).slice(0, 16) + ':00' + sign + pad(Math.floor(a / 60)) + ':' + pad(a % 60);
  }
  function isOnline(e) { return /online|zoom|virtual|youtube live/i.test(e.venue || ''); }
  /* schema.org Event (only ever produced for current/upcoming events). */
  function schema(e, origin) {
    origin = origin || 'https://mfmmegaregion2usa.org';
    var online = isOnline(e), venue = e.venue || '';
    var loc = online ? { '@type': 'VirtualLocation', url: origin + (e.page || '/events') }
      : { '@type': 'Place', name: (venue.split('—')[0].trim() || venue), address: (venue.split('—')[1] || venue).trim() };
    var o = { '@context': 'https://schema.org', '@type': 'Event', name: e.title || '',
      startDate: e.start ? isoOffset(e.start, tzOf(e)) : e.date,
      endDate: e.end ? isoOffset(e.end, tzOf(e)) : (e.start ? undefined : (e.endDate || e.date)),
      eventStatus: 'https://schema.org/EventScheduled',
      eventAttendanceMode: online ? 'https://schema.org/OnlineEventAttendanceMode' : 'https://schema.org/OfflineEventAttendanceMode',
      location: loc, image: [origin + '/' + String(e.image || '').replace(/^\//, '')],
      url: origin + (e.page || '/events'), description: e.description || '',
      organizer: { '@type': 'Organization', name: 'Mountain of Fire and Miracles Ministries — Mega Region 2 USA', url: origin + '/' } };
    if (e.link) o.offers = { '@type': 'Offer', url: e.link, availability: 'https://schema.org/InStock' };
    if (o.endDate === undefined) delete o.endDate;
    return o;
  }
  /* Real ticket/registration URL only (never "#" or empty). */
  function ticketUrl(e) { return (e && e.link && /^https?:\/\//i.test(e.link)) ? e.link : ''; }
  return { zoned: zoned, start: start, end: end, isPast: isPast, isLive: isLive, upcoming: upcoming, todayIn: todayIn,
    abbr: abbr, clock: clock, gcal: gcal, schema: schema, isOnline: isOnline, ticketUrl: ticketUrl, isoOffset: isoOffset };
})();

/* ============================================================================
   RECURRING WEEKLY PROGRAMMES
   Resolved to their next occurrence (computed in Central Time, so every visitor
   sees the same date) and given real start/end times, so countdowns, "past"
   checks and calendar links are correct across daylight-saving changes.
   Sources: WEBSITE-REFERENCE.md (HDH, Open Heaven Encounter) + the live-banner
   service windows (Tue 7:00–8:30 PM CT, Thu 6:00–7:30 PM CT) + prior live site
   data for the Weekend Deliverance session schedule.
   ========================================================================== */
(function () {
  var A = window.MFM_EVENTS, U = window.MFM_EVT; if (!A || !A.push || !U) return;
  var TZ = 'America/Chicago';
  var MON = ['January','February','March','April','May','June','July','August','September','October','November','December'];
  function pad(n) { return ('0' + n).slice(-2); }
  function ymdU(d) { return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate()); }
  var tp = U.todayIn(TZ).split('-');
  var today = new Date(Date.UTC(+tp[0], +tp[1] - 1, +tp[2]));          /* Central "today" as a UTC calendar date */
  function addDays(d, n) { var x = new Date(d.getTime()); x.setUTCDate(x.getUTCDate() + n); return x; }
  /* Next occurrence of weekday `dow` whose session (ending at endHM, CT) has not finished yet. */
  function nextDow(dow, endHM) {
    for (var k = 0; k < 8; k++) {
      var d = addDays(today, k);
      if (d.getUTCDay() !== dow) continue;
      if (U.zoned(ymdU(d) + 'T' + endHM, TZ).getTime() >= Date.now()) return d;
    }
    return addDays(today, 7);
  }
  function firstSatDate(y, m) { var d = new Date(Date.UTC(y, m, 1)); return 1 + ((6 - d.getUTCDay() + 7) % 7); }
  function rangeLabel(a, b) {
    if (a.getUTCMonth() === b.getUTCMonth()) return MON[a.getUTCMonth()] + ' ' + a.getUTCDate() + '–' + b.getUTCDate() + ', ' + b.getUTCFullYear();
    return MON[a.getUTCMonth()] + ' ' + a.getUTCDate() + ' – ' + MON[b.getUTCMonth()] + ' ' + b.getUTCDate() + ', ' + b.getUTCFullYear();
  }

  /* 1) Healing & Deliverance Hour — every Tuesday, 7:00–8:30 PM CT, online */
  var tue = ymdU(nextDow(2, '20:30'));
  A.push({
    date: tue, endDate: tue, start: tue + 'T19:00', end: tue + 'T20:30', tz: TZ,
    title: 'Healing & Deliverance Hour',
    theme: 'Weekly online prayer line · Healing · Breakthrough',
    time: '7:00 PM CT / 8:00 PM ET',
    venue: 'Online — MFM Mega Region 2 YouTube Live',
    dateDisplay: 'Every Tuesday',
    image: 'img/healing-deliverance-hour.jpg',
    alt: 'Healing & Deliverance Hour — every Tuesday, 7:00 PM CT, online prayer line',
    anchor: 'healing-deliverance-hour',
    host: 'MFM Mega Region 2 USA',
    description: 'Our weekly online prayer line — a focused hour of healing and deliverance ministry. Join us live each Tuesday for prayer against affliction, for breakthrough, and for the demonstration of God’s delivering power.',
    recurring: true
  });

  /* 2) Open Heaven Encounter — every Thursday, 6:00–7:30 PM CT, online.
        The other-country times are computed for that exact date, so they stay
        correct when the USA or UK changes clocks. */
  var thu = ymdU(nextDow(4, '19:30'));
  var ohStart = U.zoned(thu + 'T18:00', TZ);
  function at(tz) { return U.clock(ohStart, tz); }
  A.push({
    date: thu, endDate: thu, start: thu + 'T18:00', end: thu + 'T19:30', tz: TZ,
    title: 'Open Heaven Encounter',
    theme: 'A weekly prayer service',
    time: '6:00 PM CT (USA)',
    venue: 'Online — MFM Mega Region 2 YouTube Live',
    dateDisplay: 'Every Thursday',
    image: 'img/open-heaven-encounter.jpg',
    alt: 'Open Heaven Encounter — every Thursday, weekly prayer service',
    anchor: 'open-heaven-encounter',
    host: 'MFM Mega Region 2 USA',
    description: 'A weekly prayer service that draws the region together — across the USA, Ghana, the UK, Nigeria and Canada — for an encounter under an open heaven.',
    schedule: [
      { label: 'USA (Central)', when: at('America/Chicago') + ' CT' },
      { label: 'Canada (Eastern)', when: at('America/Toronto') + ' ET' },
      { label: 'United Kingdom', when: at('Europe/London') + ' UK time' },
      { label: 'Ghana', when: at('Africa/Accra') + ' GMT' },
      { label: 'Nigeria', when: at('Africa/Lagos') + ' WAT' }
    ],
    recurring: true
  });

  /* 3) Weekend Deliverance at Prayer City — every weekend EXCEPT the first of
        the month (first Saturday = PMCH). Fri 7:00 PM – Sun 2:00 PM CT. */
  (function () {
    var d = addDays(today, -((today.getUTCDay() - 5 + 7) % 7)); /* most recent Friday (<= today) */
    for (var k = 0; k < 14; k++) {
      var sat = addDays(d, 1), sun = addDays(d, 2);
      var isFirstWeekend = (sat.getUTCDate() === firstSatDate(sat.getUTCFullYear(), sat.getUTCMonth()));
      if (U.zoned(ymdU(sun) + 'T14:00', TZ).getTime() >= Date.now() && !isFirstWeekend) {
        A.push({
          date: ymdU(d), endDate: ymdU(sun), start: ymdU(d) + 'T19:00', end: ymdU(sun) + 'T14:00', tz: TZ,
          title: 'Weekend Deliverance',
          theme: 'Three days of deliverance at Prayer City',
          time: 'Fri 7:00 PM · Sat 9:00 AM & 8:00 PM · Sun 9:00 AM CT',
          venue: 'MFM USA Prayer City — 10000 Kleckley Dr, Houston, TX 77075',
          dateDisplay: 'Fri–Sun · ' + rangeLabel(d, sun),
          image: 'img/announcements/weekend-deliverance.jpg',
          alt: 'Weekend Deliverance at Prayer City — Friday through Sunday',
          anchor: 'weekend-deliverance',
          host: 'MFM USA Prayer City',
          description: 'Three days of focused deliverance ministry at MFM USA Prayer City — sustained spiritual warfare, the breaking of yokes, and the demonstration of God’s delivering power. Held every weekend except the first weekend of the month, when Power Must Change Hands takes place.',
          scripture: 'The righteous cry out, and the Lord hears them; he delivers them from all their troubles.|Psalm 34:17',
          schedule: [
            { label: 'Friday', when: '7:00 PM – 12:00 AM CT' },
            { label: 'Saturday', when: '9:00 AM – 2:00 PM CT' },
            { label: 'Saturday', when: '8:00 PM – 12:00 AM CT' },
            { label: 'Sunday', when: '9:00 AM – 2:00 PM CT' }
          ],
          recurring: true
        });
        break;
      }
      d = addDays(d, 7);
    }
  })();
})();
